swagger: '2.0'
info:
  version: 1.0.0
  title: Reservation API
  description: API to manage reservations
schemes: 
- https
host: localhost:8080
basePath: /reservartion
paths:
  /customer/{customer_id}:
    get:
      summary: Get reservation by customerID
      description: Get reservation by customerID
      operationId: getReservationByCustomerID
      parameters:
        - name: customer_id
          in: path
          description: ID of customer that needs to be fetched
          required: true
          schema:
            type: string
            format: varchar100
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Reservation not found
  /reservationNumber/{reservation_number}:
    get:
      summary: Get reservation by reservationNumber
      description: Get reservation by reservationNumber
      operationId: getReservationByReservationNumber
      parameters:
        - name: reservation_number
          in: path
          description: reservationNumber that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid number supplied
        '404':
          description: Reservation not found
  /:
    post:
      summary: Save reservation
      description: Save reservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid data to create reservation
components:
  schemas:
    Reservation:
      required:
        - name
        - photoUrls
      type: object
      properties:
        customer_id:
          type: string
          format: varchar
          example: customer20
        reservation_number:
          type: integer
          example: 20