apiVersion: v1
kind: Deployment
spec:
  containers:
    env:
    - name: ENV
      value: "LOCAL"
    - name: PORT
      value: 8080
    - name: DB_HOST
      value: "localhost"
    - name: DB_PORT
      value: 5432
    - name: DB_USER
      value: "postgres"
    - name: DB_PASSWORD
      value: "postgres"
    - name: DB_NAME
      value: "reservation"